import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ToastProvider from "./ToastProvider"; // 👈 new client component

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Skill Jackpot",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased transparent-scrollbar`}
      >
        {children}
        {/* 👇 our client-side toaster lives here */}
        <ToastProvider />
      </body>
    </html>
  );
}
